-- Upwards Event Intelligence calendar tables (used with anon key from static site).
-- Applied to project ref eghwnnvvoropndudiptr; keep in sync with Supabase dashboard.

CREATE TABLE IF NOT EXISTS public.event_votes (
  event_id integer NOT NULL,
  member_name text NOT NULL,
  vote_type text NOT NULL CHECK (vote_type IN ('up', 'down')),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT event_votes_pkey PRIMARY KEY (event_id, member_name)
);

CREATE TABLE IF NOT EXISTS public.team_members (
  name text PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.custom_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  name text NOT NULL,
  dates text,
  month text,
  location text,
  industry text,
  color text,
  score integer,
  attendance text,
  url text,
  exhibitor_url text,
  why text
);

CREATE TABLE IF NOT EXISTS public.event_overrides (
  event_id integer NOT NULL PRIMARY KEY,
  num_reps integer,
  event_days integer,
  sponsorship_cost numeric,
  convos_per_rep_per_day integer,
  updated_at timestamptz
);

ALTER TABLE public.event_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.custom_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_overrides ENABLE ROW LEVEL SECURITY;

CREATE POLICY event_votes_anon_select ON public.event_votes FOR SELECT TO anon USING (true);
CREATE POLICY event_votes_anon_insert ON public.event_votes FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY event_votes_anon_update ON public.event_votes FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY event_votes_anon_delete ON public.event_votes FOR DELETE TO anon USING (true);

CREATE POLICY team_members_anon_select ON public.team_members FOR SELECT TO anon USING (true);
CREATE POLICY team_members_anon_insert ON public.team_members FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY team_members_anon_update ON public.team_members FOR UPDATE TO anon USING (true) WITH CHECK (true);

CREATE POLICY custom_events_anon_select ON public.custom_events FOR SELECT TO anon USING (true);
CREATE POLICY custom_events_anon_insert ON public.custom_events FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY custom_events_anon_delete ON public.custom_events FOR DELETE TO anon USING (true);

CREATE POLICY event_overrides_anon_select ON public.event_overrides FOR SELECT TO anon USING (true);
CREATE POLICY event_overrides_anon_insert ON public.event_overrides FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY event_overrides_anon_update ON public.event_overrides FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY event_overrides_anon_delete ON public.event_overrides FOR DELETE TO anon USING (true);
